/* VILLMARK - artsdata + voxel-oppskrifter */

const AREAS = [
  { id:'granskogen', navn:'GRANSKOGEN', desc:'Tett barskog. Rev, ekorn og gran trives her.',
    pos:[-7,  6], farge:0x2f6b3a, kulisse:'gran', kulisseAntall:16,
    palett:[0x3c7a3e,0x458a45,0x336d38,0x4b9149],
    arter:['rev','ekorn','gran','fluesopp','kantarell','bjorn','ulv','grevling','mar',
           'radyr','storfugl','ravn','osp','blabaer','steinsopp','giftslorsopp',
           'trompetsopp','hvitveis'] },

  { id:'fjellet',    navn:'FJELLET',    desc:'Over tregrensa. Hare og gaupe jakter i steinura.',
    pos:[ 6,  7], farge:0x7d8a93, kulisse:null, kulisseAntall:0, stein:22,
    palett:[0x8d979c,0x7c868b,0x9aa3a7,0x6f797e],
    arter:['hare','gaupe','blaveis','jerv','royskatt','lemen','fossekall','roye',
           'rogn','einer','reinrose','marisko'] },

  { id:'myra',       navn:'MYRA',       desc:'Våtmark og torv. Elgen beiter i skumringen.',
    pos:[-5, -7], farge:0x6b6134, kulisse:'bjork', kulisseAntall:9,
    palett:[0x6b6134,0x5c5630,0x77713e,0x4f4a2a],
    arter:['elg','tyttebaer','molte','bjork','bever','smalom','orret','soldogg',
           'myrull','rodskrubb','graor','selje'] },

  { id:'kysten',     navn:'KYSTEN',     desc:'Knauser og furu mot havet. Hubroen ruger i berget.',
    pos:[ 7, -6], farge:0x35708a, kulisse:'furu', kulisseAntall:7,
    palett:[0x7f8e7a,0x93a08a,0x6e7d6c,0xc0b894],
    arter:['hubro','havorn','furu','hjort','piggsvin','lunde','krykkje','sild',
           'eik','barlind'] },

  { id:'vidda',      navn:'VIDDA',      desc:'Åpen høyfjellsvidde. Reinen trekker i flokk over lyngen.',
    pos:[ 1, 11], farge:0xa8895c, kulisse:null, kulisseAntall:0, stein:18, lyng:16,
    palett:[0x7a7544,0x868453,0x6b6939,0x8f8857],
    arter:['rein','rype','fjellrev','rosslyng','moskus','heilo','krekling',
           'skrubbaer','dvergbjork'] },

  { id:'fjorden',    navn:'FJORDEN',    desc:'Brekkende sjø over tareskogen. Oteren fisker i fjæra.',
    pos:[-13, -10], farge:0x2f7fae, kulisse:null, kulisseAntall:0, vann:1.2, stein:10,
    palett:[0x9a8c6a,0x8b7e5e,0xa39472,0x7f8a74],
    arter:['oter','torsk','steinkobbe','tare','havert','nise','laks','sei',
           'sukkertare','grisetang','alegras'] },
];

const SPECIES = [

  /* ---------------------------------------------------------- GRANSKOGEN */
  { id:'rev', navn:'REV', sci:'Vulpes vulpes', kind:'dyr', omrade:'granskogen',
    sjelden:2, hp:64, angrep:22, forsvar:14, fart:26, hoyde:1.6,
    fakta:'Reven hører mus under 60 cm snø og hopper rett ned gjennom skaren.',
    trekk:[{n:'MUSESPRANG',s:24},{n:'SNIKANGREP',s:18},{n:'BJEFF',s:12}],
    vox:{ type:'quadruped', len:9, hoy:5, bred:5, ben:3,
      kropp:0xd2662f, hode:0xdd7a3c, buk:0xf4e7d4, bein:0x2e2119,
      hale:{len:5, farge:0xd2662f, tupp:0xf4e7d4, bust:2},
      orer:{h:2, farge:0x2e2119}, snute:0xf4e7d4, oyne:0x171114 } },

  { id:'ekorn', navn:'EKORN', sci:'Sciurus vulgaris', kind:'dyr', omrade:'granskogen',
    sjelden:1, hp:38, angrep:14, forsvar:9, fart:34, hoyde:1.0,
    fakta:'Ekornet gjemmer nøtter på hundrevis av steder og glemmer mange av dem.',
    trekk:[{n:'NØTTEKAST',s:16},{n:'KLOSPRETT',s:12},{n:'SURR',s:8}],
    vox:{ type:'quadruped', len:6, hoy:4, bred:4, ben:2,
      kropp:0xa84a24, hode:0xb85631, buk:0xf0e0cc, bein:0x6b2f18,
      hale:{len:6, farge:0xa84a24, tupp:0xc96f3d, bust:3, opp:true},
      orer:{h:2, farge:0xa84a24, dusk:true}, snute:0xf0e0cc, oyne:0x120d0a } },

  { id:'bjorn', navn:'BJØRN', sci:'Ursus arctos', kind:'dyr', omrade:'granskogen',
    sjelden:5, hp:124, angrep:36, forsvar:30, fart:16, hoyde:2.6,
    fakta:'Binna føder i hiet midt på vinteren og sover videre mens ungene dier.',
    trekk:[{n:'RAMSLAG',s:38},{n:'KLOHOGG',s:29},{n:'REISNING',s:17}],
    vox:{ type:'quadruped', len:11, hoy:7, bred:7, ben:4,
      kropp:0x4a3526, hode:0x55402e, buk:0x3b2a1e, bein:0x2a1d14,
      hale:{len:1, farge:0x4a3526, tupp:0x4a3526, bust:1},
      orer:{h:2, farge:0x3b2a1e}, snute:0x8a7150, oyne:0x120d0a } },

  { id:'ulv', navn:'ULV', sci:'Canis lupus', kind:'dyr', omrade:'granskogen',
    sjelden:5, hp:88, angrep:33, forsvar:21, fart:30, hoyde:1.9,
    fakta:'Et ulvehyl bærer over 10 km i stille vinterluft og holder flokken samlet.',
    trekk:[{n:'FLOKKBITT',s:35},{n:'STRUPETAK',s:28},{n:'HYL',s:15}],
    vox:{ type:'quadruped', len:10, hoy:6, bred:5, ben:5,
      kropp:0x7d7b74, hode:0x8b8880, buk:0xd8d3c6, bein:0x565349,
      hale:{len:5, farge:0x6f6c65, tupp:0x33302b, bust:2},
      orer:{h:3, farge:0x565349}, snute:0x33302b, oyne:0xc9a92e } },

  { id:'gran', navn:'GRAN', sci:'Picea abies', kind:'plante', omrade:'granskogen',
    sjelden:1, hp:90, angrep:8, forsvar:34, fart:2, hoyde:4.2,
    fakta:'Old Tjikko i Sverige er en gran med rotsystem datert til 9 550 år.',
    trekk:[{n:'NÅLEREGN',s:14},{n:'ROTGREP',s:10},{n:'HARPIKS',s:12}],
    vox:{ type:'tre', hoy:13, radius:5, lov:0x2c5c33, lov2:0x3a7340, stamme:0x4a3524 } },

  { id:'fluesopp', navn:'FLUESOPP', sci:'Amanita muscaria', kind:'plante', omrade:'granskogen',
    sjelden:3, hp:42, angrep:19, forsvar:10, fart:3, hoyde:1.3,
    fakta:'Rød fluesopp er giftig, men lever i symbiose med bjørk og gran.',
    trekk:[{n:'SPORESKY',s:22},{n:'GIFTHETTE',s:17},{n:'RINGSLAG',s:9}],
    vox:{ type:'sopp', hoy:7, hatt:0xc22a25, prikk:0xf4efe4, stilk:0xf0e8d8, lamell:0xd8cdb6 } },

  { id:'kantarell', navn:'KANTARELL', sci:'Cantharellus cibarius', kind:'plante', omrade:'granskogen',
    sjelden:3, hp:36, angrep:11, forsvar:13, fart:4, hoyde:1.1,
    fakta:'Kantarellen lukter av aprikos. Den kan ikke dyrkes, bare plukkes.',
    trekk:[{n:'SPORESTØV',s:15},{n:'MYKELNETT',s:12},{n:'APRIKOSDUFT',s:8}],
    vox:{ type:'sopp', trakt:true, hoy:6, hatt:0xe0a01e, prikk:null,
      stilk:0xe8b64a, lamell:0xc88a16 } },


  { id:'grevling', navn:'GREVLING', sci:'Meles meles', kind:'dyr', omrade:'granskogen',
    sjelden:3, hp:72, angrep:24, forsvar:22, fart:18, hoyde:1.4,
    fakta:'Grevlingen graver hi som brukes av generasjon etter generasjon, noen i over hundre år.',
    trekk:[{n:'KLOGRAV',s:26},{n:'KJEVEBITT',s:22},{n:'STANKSKY',s:12}],
    vox:{ type:'quadruped', len:9, hoy:5, bred:5, ben:2,
      kropp:0x8c8a82, hode:0xf0ece2, buk:0x2a2723, bein:0x241f1b,
      hale:{len:2, farge:0x8c8a82, tupp:0xc9c5ba, bust:2},
      orer:{h:1, farge:0x2a2723}, snute:0x2a2723, oyne:0x120d0a, flekker:0x2a2723 } },

  { id:'mar', navn:'MÅR', sci:'Martes martes', kind:'dyr', omrade:'granskogen',
    sjelden:4, hp:54, angrep:23, forsvar:14, fart:33, hoyde:1.1,
    fakta:'Måren jakter i trekronene og hopper fire meter mellom greinene.',
    trekk:[{n:'GRENSPRANG',s:25},{n:'NAKKEBITT',s:21},{n:'KLATRING',s:12}],
    vox:{ type:'quadruped', len:9, hoy:4, bred:4, ben:2,
      kropp:0x5a3a24, hode:0x66442b, buk:0xe0c878, bein:0x3a2517,
      hale:{len:6, farge:0x5a3a24, tupp:0x3a2517, bust:2},
      orer:{h:2, farge:0x66442b}, snute:0x2a1c12, oyne:0x120d0a } },

  { id:'radyr', navn:'RÅDYR', sci:'Capreolus capreolus', kind:'dyr', omrade:'granskogen',
    sjelden:2, hp:68, angrep:18, forsvar:16, fart:34, hoyde:1.7,
    fakta:'Rådyret har forlenget drektighet. Egget hviler i livmora til vinteren er over.',
    trekk:[{n:'SPRANGFLUKT',s:20},{n:'GEVIRSTØT',s:22},{n:'BJEFF',s:10}],
    vox:{ type:'quadruped', len:8, hoy:6, bred:4, ben:6,
      kropp:0xa8703c, hode:0x9a6836, buk:0xe8dcc4, bein:0x6b4525,
      hale:{len:1, farge:0xffffff, tupp:0xffffff, bust:1},
      orer:{h:3, farge:0x9a6836}, snute:0x2e241c, oyne:0x120d0a,
      gevir:{spenn:3, farge:0x6b5a3a} } },

  { id:'storfugl', navn:'STORFUGL', sci:'Tetrao urogallus', kind:'dyr', omrade:'granskogen',
    sjelden:4, hp:62, angrep:22, forsvar:17, fart:20, hoyde:1.3,
    fakta:'Tiuren speller i grålysningen og hører nesten ingenting i sluttfasen av spillet.',
    trekk:[{n:'SPILLSLAG',s:24},{n:'VINGEBRAK',s:19},{n:'KNEPPING',s:11}],
    vox:{ type:'fugl', bred:6, hoy:8, dyp:5,
      kropp:0x2e3138, bryst:0x243a35, vinge:0x4a3a2a, bein:0x3a352c,
      nebb:0xe8e2d0, oyne:0x171310, strek:0xc22a25 } },

  { id:'ravn', navn:'RAVN', sci:'Corvus corax', kind:'dyr', omrade:'granskogen',
    sjelden:3, hp:58, angrep:21, forsvar:15, fart:28, hoyde:1.2,
    fakta:'Ravnen lager verktøy, husker ansikter og lever i par som holder sammen i tiår.',
    trekk:[{n:'NEBBHOGG',s:23},{n:'LURETRIKS',s:17},{n:'KORPROP',s:12}],
    vox:{ type:'fugl', bred:5, hoy:8, dyp:5,
      kropp:0x1e2026, bryst:0x2a2d34, vinge:0x14161a, bein:0x1a1a1c,
      nebb:0x121316, oyne:0x2a2a2e, strek:0x3a3f4a } },

  { id:'osp', navn:'OSP', sci:'Populus tremula', kind:'plante', omrade:'granskogen',
    sjelden:2, hp:70, angrep:9, forsvar:26, fart:3, hoyde:3.8,
    fakta:'Ospebladet står på flat stilk og skjelver i minste vinddrag.',
    trekk:[{n:'BLADSKJELV',s:13},{n:'ROTSKUDD',s:11},{n:'BARKSKJOLD',s:10}],
    vox:{ type:'lauvtre', hoy:11, kronR:4, lov:0x7aa84e, lov2:0x94bd62,
      stamme:0xbfc4b2, flekk:0x4a4e42 } },

  { id:'blabaer', navn:'BLÅBÆR', sci:'Vaccinium myrtillus', kind:'plante', omrade:'granskogen',
    sjelden:1, hp:36, angrep:10, forsvar:12, fart:5, hoyde:1.2,
    fakta:'Blåbærlyng dekker en fjerdedel av norsk skogbunn og lever i symbiose med sopp på røttene.',
    trekk:[{n:'BÆRREGN',s:13},{n:'LYNGFLETT',s:10},{n:'SAFTSPRUT',s:11}],
    vox:{ type:'baer', hoy:5, blad:0x3a6b32, blad2:0x4d8440, baer:0x3f4a8c, stilk:0x5a6b3a } },

  { id:'steinsopp', navn:'STEINSOPP', sci:'Boletus edulis', kind:'plante', omrade:'granskogen',
    sjelden:3, hp:48, angrep:12, forsvar:20, fart:3, hoyde:1.4,
    fakta:'Steinsoppen har rør i stedet for skiver under hatten. Den er Norges mest ettertraktede matsopp.',
    trekk:[{n:'RØRSPORER',s:16},{n:'TJUKKSTILK',s:13},{n:'SKOGDUFT',s:9}],
    vox:{ type:'sopp', hoy:6, hatt:0x8a5a2e, prikk:null, stilk:0xe0d4bc, lamell:0xd8cfae } },

  { id:'giftslorsopp', navn:'GIFTSLØRSOPP', sci:'Cortinarius rubellus', kind:'plante', omrade:'granskogen',
    sjelden:4, hp:40, angrep:24, forsvar:11, fart:3, hoyde:1.2,
    fakta:'Spiss giftslørsopp ødelegger nyrene, og de første symptomene kommer etter to til tre uker.',
    trekk:[{n:'NYREGIFT',s:26},{n:'SLØRSPORER',s:18},{n:'SEN VIRKNING',s:14}],
    vox:{ type:'sopp', hoy:7, hatt:0xa85a2e, prikk:null, stilk:0xb87a3c, lamell:0x8a5a2a } },

  { id:'trompetsopp', navn:'TROMPETSOPP', sci:'Craterellus cornucopioides', kind:'plante', omrade:'granskogen',
    sjelden:4, hp:34, angrep:12, forsvar:12, fart:4, hoyde:1.0,
    fakta:'Svart trompetsopp er nesten usynlig mot skogbunnen, men står i tette flokker når du først ser én.',
    trekk:[{n:'SKYGGEFORM',s:16},{n:'SPORESTØV',s:13},{n:'TRAKTGREP',s:10}],
    vox:{ type:'sopp', trakt:true, hoy:6, hatt:0x2e2822, prikk:null,
      stilk:0x3a332c, lamell:0x4a4238 } },

  { id:'hvitveis', navn:'HVITVEIS', sci:'Anemone nemorosa', kind:'plante', omrade:'granskogen',
    sjelden:1, hp:28, angrep:6, forsvar:9, fart:4, hoyde:1.0,
    fakta:'Hvitveisen dekker skogbunnen før løvet skygger. Hele planten er svakt giftig.',
    trekk:[{n:'VÅRTEPPE',s:11},{n:'JORDSTENGEL',s:9},{n:'POLLENSKY',s:8}],
    vox:{ type:'blomst', hoy:5, kron:0xf6f4ee, kron2:0xffffff, midt:0xe8dc8a,
      stilk:0x3f6b34, blad:0x2f5a2a, kinder:6 } },

  /* ---------------------------------------------------------- FJELLET */
  { id:'hare', navn:'HARE', sci:'Lepus timidus', kind:'dyr', omrade:'fjellet',
    sjelden:2, hp:46, angrep:12, forsvar:11, fart:38, hoyde:1.3,
    fakta:'Hara skifter til kritthvit vinterpels styrt av dagslengden, ikke av snøen.',
    trekk:[{n:'SIKKSAKK',s:15},{n:'BAKSPARK',s:18},{n:'DUKK',s:7}],
    vox:{ type:'quadruped', len:7, hoy:5, bred:4, ben:3,
      kropp:0xe8e6e0, hode:0xf2f1ee, buk:0xffffff, bein:0xc9c6bf,
      hale:{len:1, farge:0xffffff, tupp:0xffffff, bust:1},
      orer:{h:5, farge:0xe8e6e0, tupp:0x2b2b2b}, snute:0xd8a0a8, oyne:0x1a1418 } },

  { id:'gaupe', navn:'GAUPE', sci:'Lynx lynx', kind:'dyr', omrade:'fjellet',
    sjelden:5, hp:82, angrep:34, forsvar:20, fart:28, hoyde:1.9,
    fakta:'Gaupa er Norges eneste ville kattedyr. Labbene virker som truger i snøen.',
    trekk:[{n:'STRUPETAK',s:38},{n:'LABBESLAG',s:27},{n:'LURING',s:14}],
    vox:{ type:'quadruped', len:9, hoy:6, bred:5, ben:4,
      kropp:0xc7a271, hode:0xd4b184, buk:0xefe4d0, bein:0xa8855a,
      hale:{len:2, farge:0xc7a271, tupp:0x2b2118, bust:1},
      orer:{h:2, farge:0xc7a271, dusk:true, duskFarge:0x211a12},
      snute:0xefe4d0, oyne:0xcfa61f, flekker:0x8a6a41 } },

  { id:'jerv', navn:'JERV', sci:'Gulo gulo', kind:'dyr', omrade:'fjellet',
    sjelden:5, hp:78, angrep:31, forsvar:27, fart:19, hoyde:1.5,
    fakta:'Jerven legger kjøtt i steinur der kulda holder det ferskt til våren.',
    trekk:[{n:'KJEVEBITT',s:33},{n:'STEINRAS',s:24},{n:'MOSKUSDUFT',s:13}],
    vox:{ type:'quadruped', len:8, hoy:5, bred:5, ben:2,
      kropp:0x3b2c22, hode:0x2e221a, buk:0x2a1f18, bein:0x1f1712,
      hale:{len:3, farge:0x3b2c22, tupp:0x2a1f18, bust:2},
      orer:{h:1, farge:0x2e221a}, snute:0x1f1712, oyne:0x120d0a, flekker:0xa88a5c } },

  { id:'blaveis', navn:'BLÅVEIS', sci:'Hepatica nobilis', kind:'plante', omrade:'fjellet',
    sjelden:3, hp:30, angrep:6, forsvar:8, fart:4, hoyde:1.1,
    fakta:'Blåveisen blomstrer før løvet kommer, og fanger vårsola på skogbunnen.',
    trekk:[{n:'POLLENSKY',s:11},{n:'RANKE',s:8},{n:'DUFT',s:6}],
    vox:{ type:'blomst', hoy:6, kron:0x4a6fd4, kron2:0x7b96e8, midt:0xf0e08a,
      stilk:0x3f6b34, blad:0x2f5a2a, kinder:5 } },


  { id:'royskatt', navn:'RØYSKATT', sci:'Mustela erminea', kind:'dyr', omrade:'fjellet',
    sjelden:3, hp:40, angrep:19, forsvar:10, fart:36, hoyde:0.9,
    fakta:'Røyskatten blir kritthvit om vinteren, men halespissen står svart hele året.',
    trekk:[{n:'NAKKEBITT',s:22},{n:'SIKKSAKK',s:15},{n:'PIPING',s:9}],
    vox:{ type:'quadruped', len:8, hoy:3, bred:3, ben:1,
      kropp:0xf0eee8, hode:0xf6f5f1, buk:0xffffff, bein:0xdcd8d0,
      hale:{len:4, farge:0xf0eee8, tupp:0x1c1a18, bust:1},
      orer:{h:1, farge:0xe0dcd4}, snute:0xd8a0a8, oyne:0x120d0a } },

  { id:'lemen', navn:'LEMEN', sci:'Lemmus lemmus', kind:'dyr', omrade:'fjellet',
    sjelden:3, hp:30, angrep:15, forsvar:8, fart:24, hoyde:0.7,
    fakta:'Lemenet går til angrep på alt som kommer for nær. Bestanden topper seg hvert tredje til fjerde år.',
    trekk:[{n:'RASERIBITT',s:18},{n:'SNØGANG',s:11},{n:'HVESING',s:8}],
    vox:{ type:'quadruped', len:5, hoy:3, bred:3, ben:1,
      kropp:0xc8a33c, hode:0x2a2420, buk:0xe8d89a, bein:0x4a3a22,
      hale:{len:1, farge:0x2a2420, tupp:0x2a2420, bust:1},
      orer:{h:1, farge:0x2a2420}, snute:0x2a2420, oyne:0x120d0a, flekker:0x2a2420 } },

  { id:'fossekall', navn:'FOSSEKALL', sci:'Cinclus cinclus', kind:'dyr', omrade:'fjellet',
    sjelden:3, hp:42, angrep:16, forsvar:13, fart:29, hoyde:0.9,
    fakta:'Fossekallen er Norges nasjonalfugl og går på bunnen av iskalde elver etter larver.',
    trekk:[{n:'STRYKDYKK',s:19},{n:'ELVESTRØM',s:14},{n:'KNIKS',s:9}],
    vox:{ type:'fugl', bred:4, hoy:6, dyp:4,
      kropp:0x4a3a30, bryst:0xf2efe8, vinge:0x3a2d25, bein:0x2e2823,
      nebb:0x1e1a17, oyne:0x171310, strek:0x5c4a3a } },

  { id:'roye', navn:'RØYE', sci:'Salvelinus alpinus', kind:'dyr', omrade:'fjellet',
    sjelden:3, hp:50, angrep:17, forsvar:13, fart:26, hoyde:1.2,
    fakta:'Røya lever nordligst av alle ferskvannsfisker og står i fjellvann som er isfrie noen få uker.',
    trekk:[{n:'ISVANNSTØT',s:20},{n:'PRIKKGLANS',s:15},{n:'GYTETREKK',s:11}],
    vox:{ type:'fisk', len:10, hoy:5, bred:4,
      kropp:0x3a5a6b, hode:0x33505e, buk:0xe06a4a, finne:0xc85a3c,
      strek:0x8ab0c0, oyne:0x171310 } },

  { id:'rogn', navn:'ROGN', sci:'Sorbus aucuparia', kind:'plante', omrade:'fjellet',
    sjelden:2, hp:66, angrep:12, forsvar:24, fart:3, hoyde:3.2,
    fakta:'Rogna bærer helt opp mot tregrensa, og bærene henger til trosttrekket kommer.',
    trekk:[{n:'BÆRKLASE',s:16},{n:'GREINSVEIP',s:12},{n:'BARKSKJOLD',s:10}],
    vox:{ type:'lauvtre', hoy:10, kronR:4, lov:0x5c8a3a, lov2:0x6e9e48,
      stamme:0x6b5c4a } },

  { id:'einer', navn:'EINER', sci:'Juniperus communis', kind:'plante', omrade:'fjellet',
    sjelden:2, hp:56, angrep:11, forsvar:24, fart:2, hoyde:2.2,
    fakta:'Eineren har det videste utbredelsesområdet av alle bartrær og kan bli over tusen år.',
    trekk:[{n:'NÅLESTIKK',s:15},{n:'BÆRHARPIKS',s:12},{n:'VINDSKJOLD',s:10}],
    vox:{ type:'tre', hoy:8, radius:3, lov:0x3a5c40, lov2:0x4a6e4c, stamme:0x6b5138 } },

  { id:'reinrose', navn:'REINROSE', sci:'Dryas octopetala', kind:'plante', omrade:'fjellet',
    sjelden:3, hp:30, angrep:7, forsvar:14, fart:3, hoyde:0.8,
    fakta:'Reinrosa vokser på kalkrik grunn og vender blomsten mot sola for å varme frøene.',
    trekk:[{n:'SOLSKÅL',s:12},{n:'KALKGREP',s:10},{n:'FRØDUN',s:8}],
    vox:{ type:'blomst', hoy:4, kron:0xf4f1e6, kron2:0xffffff, midt:0xe8c23c,
      stilk:0x4a6b3a, blad:0x3a5c2e, kinder:8 } },

  { id:'marisko', navn:'MARISKO', sci:'Cypripedium calceolus', kind:'plante', omrade:'fjellet',
    sjelden:5, hp:34, angrep:9, forsvar:12, fart:3, hoyde:1.2,
    fakta:'Marisko er Norges største orkidé. Den lokker biller ned i skoen og slipper dem ut forbi pollenet.',
    trekk:[{n:'SKOFELLE',s:17},{n:'ORKIDÉDUFT',s:13},{n:'ROTSOPP',s:9}],
    vox:{ type:'blomst', hoy:6, kron:0x6b3a4a, kron2:0x8a4a5c, midt:0xf0d23c,
      stilk:0x4a6b3a, blad:0x3a5c2e, kinder:5 } },

  /* ---------------------------------------------------------- MYRA */
  { id:'elg', navn:'ELG', sci:'Alces alces', kind:'dyr', omrade:'myra',
    sjelden:4, hp:110, angrep:30, forsvar:26, fart:12, hoyde:2.8,
    fakta:'Elgoksen feller geviret hver vinter og bygger det opp igjen på én sommer.',
    trekk:[{n:'GEVIRSTØT',s:34},{n:'TRAMP',s:26},{n:'BRØL',s:15}],
    vox:{ type:'quadruped', len:11, hoy:8, bred:6, ben:6,
      kropp:0x50392a, hode:0x422f22, buk:0x3a2a1f, bein:0x261b13,
      hale:{len:1, farge:0x50392a, tupp:0x50392a, bust:0},
      orer:{h:2, farge:0x422f22}, snute:0x2b1f17, oyne:0x120d0a,
      gevir:{spenn:7, farge:0xcbb78d}, muleskjegg:0x3a2a1f } },

  { id:'tyttebaer', navn:'TYTTEBÆR', sci:'Vaccinium vitis-idaea', kind:'plante', omrade:'myra',
    sjelden:2, hp:34, angrep:9, forsvar:12, fart:5, hoyde:1.3,
    fakta:'Tyttebær holder seg friske i vann i årevis. Benzosyra konserverer dem selv.',
    trekk:[{n:'BÆRSALVE',s:12},{n:'KRATTFLETT',s:10},{n:'SYREBITT',s:14}],
    vox:{ type:'baer', hoy:5, blad:0x2f6b34, blad2:0x3f8440, baer:0xc2202c, stilk:0x4a5a32 } },

  { id:'molte', navn:'MOLTE', sci:'Rubus chamaemorus', kind:'plante', omrade:'myra',
    sjelden:4, hp:32, angrep:13, forsvar:9, fart:6, hoyde:1.2,
    fakta:'Molte kalles myras gull. Hann- og hunnplanter står hver for seg, så avlinga svikter ofte.',
    trekk:[{n:'MYRGULL',s:18},{n:'TORVGREP',s:11},{n:'SUR SAFT',s:9}],
    vox:{ type:'baer', hoy:5, blad:0x4a7a3a, blad2:0x5c8f45, baer:0xe8a33c, stilk:0x6b7a3a } },

  { id:'bjork', navn:'BJØRK', sci:'Betula pubescens', kind:'plante', omrade:'myra',
    sjelden:1, hp:74, angrep:9, forsvar:28, fart:3, hoyde:4.0,
    fakta:'Bjørka vokser høyest av alle trær i Norge og setter tregrensa i fjellet.',
    trekk:[{n:'RISKVAST',s:13},{n:'SEVJEFLOM',s:10},{n:'NEVERSKJOLD',s:11}],
    vox:{ type:'lauvtre', hoy:12, kronR:4, lov:0x5c9440, lov2:0x71a84e,
      stamme:0xe4e0d4, flekk:0x2e2a26 } },


  { id:'bever', navn:'BEVER', sci:'Castor fiber', kind:'dyr', omrade:'myra',
    sjelden:4, hp:84, angrep:23, forsvar:26, fart:14, hoyde:1.5,
    fakta:'Beveren feller trær med tennene og bygger dammer som skaper våtmark for hundrevis av arter.',
    trekk:[{n:'TREFELLING',s:27},{n:'HALESMELL',s:21},{n:'DEMNING',s:13}],
    vox:{ type:'quadruped', len:10, hoy:5, bred:5, ben:2,
      kropp:0x6b4a2e, hode:0x7a5636, buk:0x4a3320, bein:0x3a2718,
      hale:{len:4, farge:0x3a2718, tupp:0x2a1c12, bust:3},
      orer:{h:1, farge:0x4a3320}, snute:0x2a1c12, oyne:0x120d0a } },

  { id:'smalom', navn:'SMÅLOM', sci:'Gavia stellata', kind:'dyr', omrade:'myra',
    sjelden:4, hp:54, angrep:19, forsvar:15, fart:25, hoyde:1.3,
    fakta:'Smålommen hekker på små myrtjern og flyr helt ut til havet for å hente fisk til ungen.',
    trekk:[{n:'DYPDYKK',s:22},{n:'NEBBSPYD',s:17},{n:'KLAGEROP',s:11}],
    vox:{ type:'fugl', bred:5, hoy:7, dyp:6,
      kropp:0x4a4e52, bryst:0xe8e6e0, vinge:0x3a3e42, bein:0x2e3236,
      nebb:0x22262a, oyne:0xa8302a, strek:0x8a2a26 } },

  { id:'orret', navn:'ØRRET', sci:'Salmo trutta', kind:'dyr', omrade:'myra',
    sjelden:2, hp:52, angrep:19, forsvar:13, fart:28, hoyde:1.2,
    fakta:'Ørreten kjenner igjen hjemmebekken på lukt og finner tilbake dit for å gyte.',
    trekk:[{n:'STRØMSTØT',s:21},{n:'PRIKKGLANS',s:15},{n:'BEKKETREKK',s:11}],
    vox:{ type:'fisk', len:11, hoy:5, bred:4,
      kropp:0x6b6b45, hode:0x5c5c3a, buk:0xe8dcc0, finne:0x4a4a30,
      strek:0xc85a3c, oyne:0x171310 } },

  { id:'soldogg', navn:'SOLDOGG', sci:'Drosera rotundifolia', kind:'plante', omrade:'myra',
    sjelden:4, hp:32, angrep:18, forsvar:9, fart:4, hoyde:0.6,
    fakta:'Soldoggen fanger insekter i klissete dråper fordi myrjorda mangler nitrogen.',
    trekk:[{n:'LIMDRÅPE',s:20},{n:'KJERTELGREP',s:15},{n:'FORDØYELSE',s:12}],
    vox:{ type:'blomst', hoy:3, kron:0xc22a3c, kron2:0xe04a56, midt:0xf4f1e6,
      stilk:0x8a3a2e, blad:0xa8342e, kinder:6 } },

  { id:'myrull', navn:'MYRULL', sci:'Eriophorum angustifolium', kind:'plante', omrade:'myra',
    sjelden:1, hp:28, angrep:6, forsvar:11, fart:4, hoyde:1.0,
    fakta:'Myrulldusken er frøull, ikke blomst. Vinden bærer den ut over myra.',
    trekk:[{n:'ULLDUSK',s:11},{n:'TORVROT',s:9},{n:'VINDSPREDNING',s:7}],
    vox:{ type:'blomst', hoy:6, kron:0xf4f2ec, kron2:0xffffff, midt:0xe8e4d8,
      stilk:0x6b7a3a, blad:0x5a6b30, kinder:7 } },

  { id:'rodskrubb', navn:'RØDSKRUBB', sci:'Leccinum aurantiacum', kind:'plante', omrade:'myra',
    sjelden:3, hp:44, angrep:13, forsvar:17, fart:3, hoyde:1.5,
    fakta:'Rødskrubben blir blåsvart i snittflaten i løpet av noen minutter.',
    trekk:[{n:'SNITTSVERTING',s:15},{n:'RØRSPORER',s:13},{n:'SKJELLSTILK',s:10}],
    vox:{ type:'sopp', hoy:7, hatt:0xc45a22, prikk:null, stilk:0xe4dcc8, lamell:0xd0c6a8 } },

  { id:'graor', navn:'GRÅOR', sci:'Alnus incana', kind:'plante', omrade:'myra',
    sjelden:1, hp:64, angrep:9, forsvar:25, fart:3, hoyde:3.4,
    fakta:'Gråora binder nitrogen fra lufta med bakterier i rotknollene og gjødsler sin egen mark.',
    trekk:[{n:'ROTKNOLL',s:13},{n:'LØVSKYGGE',s:11},{n:'SEVJEFLOM',s:9}],
    vox:{ type:'lauvtre', hoy:10, kronR:4, lov:0x4a7a3e, lov2:0x5c8f4a,
      stamme:0x8a8a82 } },

  { id:'selje', navn:'SELJE', sci:'Salix caprea', kind:'plante', omrade:'myra',
    sjelden:2, hp:58, angrep:10, forsvar:22, fart:4, hoyde:2.8,
    fakta:'Selja blomstrer før løvsprett og gir humlene den første pollenen om våren.',
    trekk:[{n:'GÅSUNGE',s:14},{n:'PILEFLETT',s:11},{n:'TIDLIGPOLLEN',s:10}],
    vox:{ type:'lauvtre', hoy:9, kronR:4, lov:0x8a9e5a, lov2:0x9eb06a,
      stamme:0x6b5f4a } },

  /* ---------------------------------------------------------- KYSTEN */
  { id:'hubro', navn:'HUBRO', sci:'Bubo bubo', kind:'dyr', omrade:'kysten',
    sjelden:5, hp:70, angrep:29, forsvar:18, fart:24, hoyde:1.5,
    fakta:'Hubroen er Europas største ugle. Vingespennet når 180 cm.',
    trekk:[{n:'STUPANGREP',s:33},{n:'KLOGREP',s:25},{n:'UHU-ROP',s:13}],
    vox:{ type:'fugl', bred:6, hoy:8, dyp:5,
      kropp:0x8a6b45, bryst:0xc6a877, vinge:0x6d5436, bein:0xd0a13f,
      orer:{h:2, farge:0x6d5436}, nebb:0x2a2320, oyne:0xe8a41c, strek:0x4e3b26 } },

  { id:'havorn', navn:'HAVØRN', sci:'Haliaeetus albicilla', kind:'dyr', omrade:'kysten',
    sjelden:4, hp:76, angrep:32, forsvar:19, fart:27, hoyde:1.8,
    fakta:'Havørna har Nord-Europas største vingespenn og kan bli over 30 år gammel.',
    trekk:[{n:'FISKEGREP',s:34},{n:'VINGESLAG',s:23},{n:'SKRIK',s:14}],
    vox:{ type:'fugl', bred:7, hoy:9, dyp:5,
      kropp:0x6b5a46, bryst:0x9a8a74, vinge:0x4f4234, bein:0xe0b13c,
      nebb:0xe8c23c, oyne:0xd8c03a, strek:0xe8e4da, hale:0xf0ece2 } },

  { id:'furu', navn:'FURU', sci:'Pinus sylvestris', kind:'plante', omrade:'kysten',
    sjelden:1, hp:86, angrep:10, forsvar:32, fart:2, hoyde:4.6,
    fakta:'Furua på karrig kyst kan bli 700 år. Malmveden er nesten råtefri.',
    trekk:[{n:'KONGLEKAST',s:15},{n:'BARKSKJOLD',s:9},{n:'TJÆREDRYPP',s:12}],
    vox:{ type:'tre', form:'furu', hoy:14, radius:5,
      lov:0x3f6b33, lov2:0x4d7d3c, stamme:0x9a5f34 } },


  { id:'hjort', navn:'HJORT', sci:'Cervus elaphus', kind:'dyr', omrade:'kysten',
    sjelden:3, hp:98, angrep:27, forsvar:23, fart:31, hoyde:2.3,
    fakta:'Hjortebrunsten i september fyller vestlandsliene med brøl som bærer over hele dalen.',
    trekk:[{n:'BRUNSTSTØT',s:30},{n:'GEVIRKAMP',s:25},{n:'BRØL',s:14}],
    vox:{ type:'quadruped', len:10, hoy:7, bred:5, ben:6,
      kropp:0x8a6a45, hode:0x7a5c3a, buk:0xd8c8a8, bein:0x5c4530,
      hale:{len:1, farge:0xe8d8b8, tupp:0xe8d8b8, bust:1},
      orer:{h:3, farge:0x7a5c3a}, snute:0x3a2e24, oyne:0x120d0a,
      gevir:{spenn:7, farge:0x8a7a52} } },

  { id:'piggsvin', navn:'PIGGSVIN', sci:'Erinaceus europaeus', kind:'dyr', omrade:'kysten',
    sjelden:3, hp:48, angrep:14, forsvar:28, fart:10, hoyde:0.8,
    fakta:'Piggsvinet har rundt 6000 pigger og ruller seg til kule med en muskel langs ryggen.',
    trekk:[{n:'PIGGKULE',s:20},{n:'RULLEVERN',s:16},{n:'SNUSING',s:8}],
    vox:{ type:'quadruped', len:7, hoy:4, bred:5, ben:1,
      kropp:0x6b5a3a, hode:0xb8a082, buk:0xd8c8a8, bein:0x4a3a26,
      hale:{len:1, farge:0x6b5a3a, tupp:0x6b5a3a, bust:1},
      orer:{h:1, farge:0xb8a082}, snute:0x2a2420, oyne:0x120d0a, flekker:0xe8e0cc } },

  { id:'lunde', navn:'LUNDE', sci:'Fratercula arctica', kind:'dyr', omrade:'kysten',
    sjelden:4, hp:46, angrep:15, forsvar:14, fart:30, hoyde:0.9,
    fakta:'Lunden bærer et titalls sil på tvers i nebbet samtidig, holdt fast av pigger i ganen.',
    trekk:[{n:'STUPDYKK',s:20},{n:'NEBBLAST',s:18},{n:'VINGESURR',s:12}],
    vox:{ type:'fugl', bred:5, hoy:6, dyp:4,
      kropp:0x1e2024, bryst:0xf4f2ec, vinge:0x14161a, bein:0xe86a1c,
      nebb:0xe84a22, oyne:0x171310, strek:0xc8c4ba } },

  { id:'krykkje', navn:'KRYKKJE', sci:'Rissa tridactyla', kind:'dyr', omrade:'kysten',
    sjelden:4, hp:44, angrep:16, forsvar:12, fart:32, hoyde:1.0,
    fakta:'Krykkja hekker på loddrette berghyller. Bestanden har falt over 80 prosent siden 1980.',
    trekk:[{n:'HYLLEDYKK',s:19},{n:'VINGEKAST',s:15},{n:'KRYKKJEROP',s:10}],
    vox:{ type:'fugl', bred:5, hoy:6, dyp:4,
      kropp:0xdcdde0, bryst:0xf8f8f6, vinge:0x8a929a, bein:0x2a2c2e,
      nebb:0xd8c23c, oyne:0x171310, strek:0x2a2c2e } },

  { id:'sild', navn:'SILD', sci:'Clupea harengus', kind:'dyr', omrade:'kysten',
    sjelden:2, hp:40, angrep:14, forsvar:11, fart:30, hoyde:1.0,
    fakta:'Sildestimen kan telle milliarder og snur som én kropp når en predator kommer.',
    trekk:[{n:'STIMVIRVEL',s:18},{n:'SØLVGLIMT',s:14},{n:'SPRUT',s:9}],
    vox:{ type:'fisk', len:9, hoy:4, bred:3,
      kropp:0x8a98a8, hode:0x7a889a, buk:0xf0f2f4, finne:0x6b7886,
      strek:0xc8d2da, oyne:0x171310 } },

  { id:'eik', navn:'EIK', sci:'Quercus robur', kind:'plante', omrade:'kysten',
    sjelden:3, hp:96, angrep:12, forsvar:36, fart:2, hoyde:4.4,
    fakta:'En gammel eik kan huse over tusen arter insekter, lav og sopp.',
    trekk:[{n:'NØTTEFALL',s:16},{n:'GREINVEKT',s:14},{n:'BARKSKJOLD',s:13}],
    vox:{ type:'lauvtre', hoy:12, kronR:6, lov:0x4a7a32, lov2:0x5c8f3e,
      stamme:0x5c4a36 } },

  { id:'barlind', navn:'BARLIND', sci:'Taxus baccata', kind:'plante', omrade:'kysten',
    sjelden:4, hp:72, angrep:16, forsvar:30, fart:2, hoyde:2.6,
    fakta:'Hele barlinden er giftig unntatt det røde bærkjøttet. Veden ble brukt til langbuer.',
    trekk:[{n:'TAKSINGIFT',s:22},{n:'BUEVED',s:15},{n:'SKYGGEVEKST',s:11}],
    vox:{ type:'tre', hoy:9, radius:4, lov:0x2a4a32, lov2:0x35593c, stamme:0x7a4a38 } },

  /* ---------------------------------------------------------- VIDDA */
  { id:'rein', navn:'REIN', sci:'Rangifer tarandus', kind:'dyr', omrade:'vidda',
    sjelden:3, hp:96, angrep:24, forsvar:24, fart:29, hoyde:2.4,
    fakta:'Reinen ser ultrafiolett lys og kan se lav og ulvepels mot snøen.',
    trekk:[{n:'FLOKKTRAMP',s:29},{n:'GEVIRFEIE',s:25},{n:'SNØGRAV',s:14}],
    vox:{ type:'quadruped', len:10, hoy:6, bred:5, ben:6,
      kropp:0x8c7a63, hode:0x7a6a56, buk:0xe0d8c8, bein:0x5c4f40,
      hale:{len:1, farge:0xe0d8c8, tupp:0xe0d8c8, bust:1},
      orer:{h:2, farge:0x7a6a56}, snute:0x4a3f33, oyne:0x120d0a,
      gevir:{spenn:9, farge:0xd8c9a8} } },

  { id:'rype', navn:'LIRYPE', sci:'Lagopus lagopus', kind:'dyr', omrade:'vidda',
    sjelden:2, hp:44, angrep:13, forsvar:12, fart:31, hoyde:1.1,
    fakta:'Lirypa har fjær helt ned på tærne. Beina virker som truger på skaren.',
    trekk:[{n:'OPPFLUKT',s:17},{n:'SKARELØP',s:13},{n:'LATTERROP',s:9}],
    vox:{ type:'fugl', bred:5, hoy:6, dyp:4,
      kropp:0xf0ece2, bryst:0xffffff, vinge:0xdcd6c8, bein:0xe8e2d4,
      nebb:0x2e2a26, oyne:0x171310, strek:0xb8a888 } },

  { id:'fjellrev', navn:'FJELLREV', sci:'Vulpes lagopus', kind:'dyr', omrade:'vidda',
    sjelden:5, hp:58, angrep:21, forsvar:16, fart:30, hoyde:1.4,
    fakta:'Fjellreven tåler 50 minusgrader. Den er blant Norges mest truede pattedyr.',
    trekk:[{n:'SNØSPRANG',s:26},{n:'ISBITT',s:19},{n:'PIPING',s:11}],
    vox:{ type:'quadruped', len:8, hoy:5, bred:5, ben:2,
      kropp:0xe6e8ea, hode:0xf2f4f6, buk:0xffffff, bein:0xcdd2d6,
      hale:{len:5, farge:0xe6e8ea, tupp:0xffffff, bust:3},
      orer:{h:2, farge:0xd6dade}, snute:0x2a2a2e, oyne:0x171114 } },

  { id:'rosslyng', navn:'RØSSLYNG', sci:'Calluna vulgaris', kind:'plante', omrade:'vidda',
    sjelden:1, hp:40, angrep:7, forsvar:17, fart:3, hoyde:1.1,
    fakta:'Røsslyng kan bli 40 år. Lyngheiene langs kysten er holdt åpne av brenning i 5000 år.',
    trekk:[{n:'LYNGTEPPE',s:12},{n:'ROTFLETT',s:10},{n:'HONNINGDUFT',s:8}],
    vox:{ type:'baer', hoy:5, blad:0x4e5f36, blad2:0x63763f, baer:0xb464a8, stilk:0x6b5a3a } },


  { id:'moskus', navn:'MOSKUS', sci:'Ovibos moschatus', kind:'dyr', omrade:'vidda',
    sjelden:5, hp:130, angrep:34, forsvar:34, fart:14, hoyde:2.2,
    fakta:'Moskusflokken stiller seg i ring med hornene ut mot rovdyret. Dovreflokken stammer fra Grønland.',
    trekk:[{n:'HORNSTØT',s:36},{n:'RINGVERN',s:26},{n:'TRAMP',s:18}],
    vox:{ type:'quadruped', len:11, hoy:7, bred:7, ben:3,
      kropp:0x2e2620, hode:0x3a3028, buk:0x241d18, bein:0xc8bca0,
      hale:{len:1, farge:0x2e2620, tupp:0x2e2620, bust:1},
      orer:{h:1, farge:0x3a3028}, snute:0x1e1a16, oyne:0x120d0a,
      gevir:{spenn:5, farge:0xd8cba8}, muleskjegg:0x241d18 } },

  { id:'heilo', navn:'HEILO', sci:'Pluvialis apricaria', kind:'dyr', omrade:'vidda',
    sjelden:2, hp:40, angrep:13, forsvar:11, fart:33, hoyde:0.9,
    fakta:'Heiloen lokker rovdyr vekk fra reiret ved å halte som om vingen er brukket.',
    trekk:[{n:'LOKKEHALT',s:16},{n:'VIDDESPURT',s:14},{n:'FLØYTEROP',s:9}],
    vox:{ type:'fugl', bred:5, hoy:6, dyp:4,
      kropp:0x5c5a34, bryst:0x1e1c18, vinge:0x4a4828, bein:0x3a3830,
      nebb:0x22201c, oyne:0x171310, strek:0xe8d86a } },

  { id:'krekling', navn:'KREKLING', sci:'Empetrum nigrum', kind:'plante', omrade:'vidda',
    sjelden:1, hp:34, angrep:8, forsvar:15, fart:3, hoyde:0.8,
    fakta:'Kreklingen skiller ut stoffer som hemmer andre planter og kan dekke vidda i tette matter.',
    trekk:[{n:'SVARTBÆR',s:12},{n:'MATTEGREP',s:11},{n:'HEMMESTOFF',s:10}],
    vox:{ type:'baer', hoy:4, blad:0x2e4a32, blad2:0x3a5c3c, baer:0x1a1a22, stilk:0x4a3a28 } },

  { id:'skrubbaer', navn:'SKRUBBÆR', sci:'Cornus suecica', kind:'plante', omrade:'vidda',
    sjelden:2, hp:32, angrep:9, forsvar:11, fart:4, hoyde:0.9,
    fakta:'Skrubbærets svarte blomst sitter midt i fire hvite høyblad som ser ut som kronblad.',
    trekk:[{n:'BÆRKLASE',s:13},{n:'HØYBLAD',s:10},{n:'ROTSKUDD',s:8}],
    vox:{ type:'baer', hoy:5, blad:0x4a7a3e, blad2:0x5c8f4a, baer:0xc43a2a, stilk:0x5a6b3a } },

  { id:'dvergbjork', navn:'DVERGBJØRK', sci:'Betula nana', kind:'plante', omrade:'vidda',
    sjelden:1, hp:44, angrep:8, forsvar:19, fart:3, hoyde:1.2,
    fakta:'Dvergbjørka holder seg under snødekket om vinteren og slipper unna frostbrann.',
    trekk:[{n:'SNØLY',s:12},{n:'RISKVAST',s:10},{n:'ROTFLETT',s:9}],
    vox:{ type:'lauvtre', hoy:5, kronR:3, lov:0x6b8a3a, lov2:0x7d9e48,
      stamme:0x5c4a3a } },

  /* ---------------------------------------------------------- FJORDEN */
  { id:'oter', navn:'OTER', sci:'Lutra lutra', kind:'dyr', omrade:'fjorden',
    sjelden:4, hp:66, angrep:25, forsvar:17, fart:32, hoyde:1.3,
    fakta:'Oteren har 50 000 hår per kvadratcentimeter. Pelsen holder lufta og varmen inne.',
    trekk:[{n:'DYKKBITT',s:28},{n:'HALESLAG',s:20},{n:'PLASK',s:12}],
    vox:{ type:'quadruped', len:11, hoy:4, bred:4, ben:1,
      kropp:0x5c4433, hode:0x6b5240, buk:0xc0ac92, bein:0x4a3628,
      hale:{len:6, farge:0x5c4433, tupp:0x4a3628, bust:2},
      orer:{h:1, farge:0x4a3628}, snute:0xc0ac92, oyne:0x120d0a } },

  { id:'torsk', navn:'TORSK', sci:'Gadus morhua', kind:'dyr', omrade:'fjorden',
    sjelden:2, hp:52, angrep:18, forsvar:14, fart:22, hoyde:1.4,
    fakta:'Skreien svømmer 1000 km fra Barentshavet til Lofoten for å gyte hver vinter.',
    trekk:[{n:'STIMSTØT',s:21},{n:'SUGEGAP',s:16},{n:'SKREITREKK',s:11}],
    vox:{ type:'fisk', len:12, hoy:6, bred:4,
      kropp:0x8a8259, hode:0x7a7350, buk:0xe4dcc4, finne:0x6b6445,
      strek:0xd8d0b4, oyne:0x171310, skjegg:0xc0b894 } },

  { id:'steinkobbe', navn:'STEINKOBBE', sci:'Phoca vitulina', kind:'dyr', omrade:'fjorden',
    sjelden:3, hp:86, angrep:20, forsvar:25, fart:18, hoyde:1.5,
    fakta:'Steinkobben kan holde pusten i nesten en halvtime og sove under vann.',
    trekk:[{n:'KASTEBYLGE',s:24},{n:'LUFFESLAG',s:18},{n:'BJEFF',s:10}],
    vox:{ type:'sel', len:11, hoy:5, bred:5,
      kropp:0x8f9296, hode:0x9ba0a4, buk:0xd8dcdd, luffe:0x6f7276,
      snute:0x4a4d50, oyne:0x120d0a, flekker:0x5a5e62 } },

  { id:'tare', navn:'STORTARE', sci:'Laminaria hyperborea', kind:'plante', omrade:'fjorden',
    sjelden:2, hp:58, angrep:8, forsvar:22, fart:7, hoyde:2.6,
    fakta:'Tareskogen langs norskekysten er blant havets mest artsrike skoger.',
    trekk:[{n:'TANGGREP',s:14},{n:'BØLGESLAG',s:12},{n:'SLIMHINNE',s:9}],
    vox:{ type:'tare', hoy:11, blader:5, bladLen:5,
      stilk:0x6b4a22, fot:0x4a3318, blad:0x5c6b28, blad2:0x74853a } },

  { id:'havert', navn:'HAVERT', sci:'Halichoerus grypus', kind:'dyr', omrade:'fjorden',
    sjelden:4, hp:104, angrep:26, forsvar:28, fart:17, hoyde:1.9,
    fakta:'Haverten føder hvite unger på land om høsten. Hannen kan bli tre meter lang.',
    trekk:[{n:'KJEVEGAP',s:28},{n:'VEKTKAST',s:22},{n:'BRØL',s:12}],
    vox:{ type:'sel', len:13, hoy:6, bred:6,
      kropp:0x5c5a52, hode:0x6b685e, buk:0xc0bcae, luffe:0x45433c,
      snute:0x2e2c28, oyne:0x120d0a, flekker:0x3a3832 } },

  { id:'nise', navn:'NISE', sci:'Phocoena phocoena', kind:'dyr', omrade:'fjorden',
    sjelden:4, hp:88, angrep:24, forsvar:22, fart:34, hoyde:1.6,
    fakta:'Nisa er verdens minste tannhval og finner fisk med klikkelyder over 100 kHz.',
    trekk:[{n:'EKKOLODD',s:26},{n:'STIMJAKT',s:22},{n:'PUSTESPRUT',s:12}],
    vox:{ type:'sel', len:13, hoy:5, bred:5,
      kropp:0x2e3338, hode:0x3a4046, buk:0xe4e6e8, luffe:0x22262a,
      snute:0x1a1e22, oyne:0x120d0a } },

  { id:'laks', navn:'LAKS', sci:'Salmo salar', kind:'dyr', omrade:'fjorden',
    sjelden:3, hp:62, angrep:22, forsvar:15, fart:33, hoyde:1.5,
    fakta:'Laksen vokser i havet og finner tilbake til sin egen elv på lukt for å gyte.',
    trekk:[{n:'FOSSESPRANG',s:25},{n:'SØLVSTØT',s:20},{n:'ELVETREKK',s:18}],
    vox:{ type:'fisk', len:13, hoy:6, bred:4,
      kropp:0x8a98a4, hode:0x7a8894, buk:0xf2f2f0, finne:0x5c6a76,
      strek:0xc8d0d8, oyne:0x171310 } },

  { id:'sei', navn:'SEI', sci:'Pollachius virens', kind:'dyr', omrade:'fjorden',
    sjelden:1, hp:48, angrep:17, forsvar:13, fart:27, hoyde:1.3,
    fakta:'Seien går i store stimer under kaikanten og jager sild i overflata.',
    trekk:[{n:'STIMSTØT',s:19},{n:'KAIJAKT',s:15},{n:'SPRUT',s:10}],
    vox:{ type:'fisk', len:11, hoy:5, bred:4,
      kropp:0x3a4a45, hode:0x33423e, buk:0xe0e4e0, finne:0x2a3a35,
      strek:0xd8dcd8, oyne:0x171310 } },

  { id:'sukkertare', navn:'SUKKERTARE', sci:'Saccharina latissima', kind:'plante', omrade:'fjorden',
    sjelden:1, hp:50, angrep:7, forsvar:20, fart:7, hoyde:2.2,
    fakta:'Sukkertaren får et hvitt sukkerbelegg når den tørker. Den har forsvunnet fra store deler av Sørlandet.',
    trekk:[{n:'BØLGESVEIP',s:12},{n:'SUKKERHINNE',s:10},{n:'FESTEGREP',s:9}],
    vox:{ type:'tare', hoy:10, blader:3, bladLen:6,
      stilk:0x7a5a2a, fot:0x4a3318, blad:0x6b6b2a, blad2:0x86863c } },

  { id:'grisetang', navn:'GRISETANG', sci:'Ascophyllum nodosum', kind:'plante', omrade:'fjorden',
    sjelden:1, hp:54, angrep:9, forsvar:23, fart:6, hoyde:1.8,
    fakta:'Grisetang setter én luftblære i året. Planter med over femti blærer er vanlige.',
    trekk:[{n:'BLÆREFLYT',s:13},{n:'TANGPISK',s:11},{n:'FJÆREGREP',s:10}],
    vox:{ type:'tare', hoy:8, blader:6, bladLen:4,
      stilk:0x6b5a22, fot:0x4a3a18, blad:0x8a7a2a, blad2:0xa08c3a } },

  { id:'alegras', navn:'ÅLEGRAS', sci:'Zostera marina', kind:'plante', omrade:'fjorden',
    sjelden:2, hp:42, angrep:6, forsvar:18, fart:8, hoyde:1.4,
    fakta:'Ålegras er en blomsterplante, ikke tang. Engene er barnehage for torskeyngel.',
    trekk:[{n:'ENGSVEIP',s:11},{n:'RHIZOMGREP',s:10},{n:'BØLGEDEMP',s:9}],
    vox:{ type:'tare', hoy:9, blader:7, bladLen:5,
      stilk:0x5c7a3a, fot:0x4a5c2a, blad:0x6b9e3a, blad2:0x7fb44a } },
];

const SPECIES_BY_ID = Object.fromEntries(SPECIES.map(s => [s.id, s]));

/* ---------------------------------------------------------- varianter */
const VARIANTER = {
  albino:   { navn:'ALBINO',   bonus:1.35, sjanse:0.035 },
  melanist: { navn:'MELANIST', bonus:1.30, sjanse:0.030 },
  gyllen:   { navn:'GYLLEN',   bonus:1.50, sjanse:0.015 },
};

/* ---------------------------------------------------------- butikk */
/* Hver vare er EN ting. Du kjoper en om gangen og setter den ut for haand.
   vri:'senter' snur tingen mot midten av plenen, 'fri' gir tilfeldig vinkel. */
const BUTIKK = [
  { id:'helle',      navn:'STEINHELLE',  pris:5,   ikon:'&#9638;',  vox:'_helle',      skala:1,    vri:'fri',
    desc:'Legg helle etter helle til en sti.' },
  { id:'blomst',     navn:'VILLBLOMST',  pris:8,   ikon:'&#10047;', vox:'_blomst',     skala:0.85, vri:'fri',
    desc:'En tust ville blomster.' },
  { id:'stolpe',     navn:'SKIGARDSFAG', pris:10,  ikon:'&#9776;',  vox:'_gjerde',     skala:1,    vri:'senter',
    desc:'Ett fag skigard. Sett flere i rad.' },
  { id:'stein',      navn:'KAMPESTEIN',  pris:12,  ikon:'&#9679;',  vox:'_stein',      skala:1,    vri:'fri',
    desc:'Rund stein fra bekken.' },
  { id:'stubbe',     navn:'TRESTUBBE',   pris:18,  ikon:'&#9711;',  vox:'_stubbe',     skala:1,    vri:'fri',
    desc:'Stubbe etter et felt tre.' },
  { id:'busk',       navn:'BUSK',        pris:20,  ikon:'&#9827;',  vox:'_busk',       skala:1,    vri:'fri',
    desc:'Lav busk med tett lauv.' },
  { id:'hekk',       navn:'HEKKFELT',    pris:22,  ikon:'&#9608;',  vox:'_hekk',       skala:1,    vri:'senter',
    desc:'Ett hekkfelt. Sett flere i rad til en vegg.' },
  { id:'lykt',       navn:'LYKT',        pris:25,  ikon:'&#9728;',  vox:'_lykt',       skala:1,    vri:'fri',
    desc:'Lykt som lyser opp stien.' },
  { id:'skilt',      navn:'SKILT',       pris:28,  ikon:'&#9872;',  vox:'_skilt',      skala:1,    vri:'senter',
    desc:'Treskilt paa stolpe.' },
  { id:'ved',        navn:'VEDSTABEL',   pris:30,  ikon:'&#9776;',  vox:'_ved',        skala:1,    vri:'senter',
    desc:'Stabel med kloyvd ved.' },
  { id:'fuglekasse', navn:'FUGLEKASSE',  pris:35,  ikon:'&#9730;',  vox:'_fuglekasse', skala:1,    vri:'senter',
    desc:'Kasse paa stolpe. Fuglene liker den.' },
  { id:'benk',       navn:'BENK',        pris:40,  ikon:'&#9641;',  vox:'_benk',       skala:1,    vri:'senter',
    desc:'Sitteplass med utsikt.' },
  { id:'fuglebad',   navn:'FUGLEBAD',    pris:55,  ikon:'&#9737;',  vox:'_fuglebad',   skala:1,    vri:'fri',
    desc:'Steinskaal med vann.' },
  { id:'baal',       navn:'B\u00c5LPLASS',  pris:60,  ikon:'&#9832;',  vox:'_baal',       skala:1,    vri:'fri',
    desc:'Steinring med baal i midten.' },
  { id:'flagg',      navn:'FLAGGSTANG',  pris:70,  ikon:'&#9872;',  vox:'_flagg',      skala:1,    vri:'senter',
    desc:'Stang med flagg paa toppen.' },
  { id:'telt',       navn:'TELT',        pris:90,  ikon:'&#9650;',  vox:'_telt',       skala:1,    vri:'senter',
    desc:'Lavvo av seilduk.' },
  { id:'dam',        navn:'DAM',         pris:260, ikon:'&#9781;',  vox:null,          skala:1,    vri:'fri',
    desc:'Vannspeil med steinkant. Sett vannartene i den.' },
];
const BUTIKK_BY_ID = Object.fromEntries(BUTIKK.map(b => [b.id, b]));

/* ---------------------------------------------------------- sesonger */
const SESONGER = ['vaar','sommer','host','vinter'];
const SESONG_NAVN = { vaar:'VÅR', sommer:'SOMMER', host:'HØST', vinter:'VINTER' };
const SESONG_HIMMEL = { vaar:0xa8d8ef, sommer:0x9ed0ef, host:0xb0c2cc, vinter:0xc9d9e6 };
